export const SET_NOTE_LIST = 'SET_NOTE_LIST';
export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE';
export const SET_LOADING_NOTE = 'SET_LOADING_NOTE';
export const SET_LOADING_LIST = 'SET_LOADING_LIST';